In [100]:
!pip install pandas --break-system-packages
!pip install scikit-learn --break-system-packages

Requirement already satisfied: pandas in ./venv/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in ./venv/lib/python3.13/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: scikit-learn in ./venv/lib/python3.13/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in ./venv/lib/python3.13/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in ./venv/lib/python3.13/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in ./venv/lib/python3.13/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./venv/lib/python3.13/site-packages (from scikit-learn) (3.6.0)

In [101]:
pip install --upgrade pip

Requirement already satisfied: pip in ./venv/lib/python3.13/site-packages (26.0.1)
Note: you may need to restart the kernel to use updated packages.

In [102]:
pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in ./venv/lib/python3.13/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in ./venv/lib/python3.13/site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in ./venv/lib/python3.13/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in ./venv/lib/python3.13/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./venv/lib/python3.13/site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [103]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

In [104]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [105]:
df['age'] = df['age'].fillna(df['age'].median(), inplace=True)

/var/folders/nw/lm1tqhsj2jjcs6bl14pw4xlm0000gq/T/ipykernel_11348/3812779953.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['age'] = df['age'].fillna(df['age'].median(), inplace=True)

In [106]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [107]:
df['city'].mode()

0     Delhi
1    Mumbai
Name: city, dtype: str

In [108]:
df['city'] = df['city'].fillna(df['city'].mode()[0], inplace=True)

/var/folders/nw/lm1tqhsj2jjcs6bl14pw4xlm0000gq/T/ipykernel_11348/2316145129.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['city'] = df['city'].fillna(df['city'].mode()[0], inplace=True)

In [109]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0   Delhi    Male          95000

In [110]:

onehot_encoder = OneHotEncoder()

In [ ]:
one_hot_encoded = onehot_encoder.fit_transform(df[['city']])

one_hot_encoded_df = pd.DataFrame(one_hot_encoded.toarray(), columns=onehot_encoder.get_feature_names_out(['city']))

df = pd.concat([df, one_hot_encoded_df], axis=1)

   customer_id   age    city  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0  Mumbai    Male          40000         0.0          1.0
1            2  35.0   Delhi  Female          80000         1.0          0.0
2            3  35.0   Delhi  Female          60000         1.0          0.0
3            4  35.0  Mumbai    Male         120000         0.0          1.0
4            2  35.0   Delhi  Female          80000         1.0          0.0
5            5  40.0   Delhi    Male          95000         1.0          0.0

In [ ]:
label_encoder = LabelEncoder()

df['age'] = label_encoder.fit_transform(df['gender'])

   customer_id  age    city  gender  annual_income  city_Delhi  city_Mumbai
0            1    1  Mumbai    Male          40000         0.0          1.0
1            2    0   Delhi  Female          80000         1.0          0.0
2            3    0   Delhi  Female          60000         1.0          0.0
3            4    1  Mumbai    Male         120000         0.0          1.0
4            2    0   Delhi  Female          80000         1.0          0.0
5            5    1   Delhi    Male          95000         1.0          0.0