# Create a pandas DataFrame using the employee data

In [5]:
import pandas as pd

# dataframe = pd.read_csv("employee.csv")
data = {
    "EmployeeID": [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
    "Name": ["Sarah", "Michael", "Jennifer", "David", "Lisa", "James", "Emma", "Robert", "Sophia", "William"],
    "Department": ["Engineering", "Sales", "Marketing", "Engineering", "HR", "Sales", "Engineering", "Marketing", "Sales", "HR"],
    "Salary": [85000, 62000, 71000, 92000, 58000, 68000, 78000, 75000, 65000, 60000],
    "Experience": [4, 3, 5, 5, 4, 4, 3, 4, 5, 3],
    "Rating": [5, 3, 7, 8, 4, 6, 2, 5, 4, 3]
}
dataframe = pd.DataFrame(data)
dataframe

   EmployeeID      Name   Department  Salary  Experience  Rating
0         201     Sarah  Engineering   85000           4       5
1         202   Michael        Sales   62000           3       3
2         203  Jennifer    Marketing   71000           5       7
3         204     David  Engineering   92000           5       8
4         205      Lisa           HR   58000           4       4
5         206     James        Sales   68000           4       6
6         207      Emma  Engineering   78000           3       2
7         208    Robert    Marketing   75000           4       5
8         209    Sophia        Sales   65000           5       4
9         210   William           HR   60000           3       3

# how coloumns with Name, Department and Salary.

In [6]:
dataframe[['Name', 'Department', 'Salary']]

       Name   Department  Salary
0     Sarah  Engineering   85000
1   Michael        Sales   62000
2  Jennifer    Marketing   71000
3     David  Engineering   92000
4      Lisa           HR   58000
5     James        Sales   68000
6      Emma  Engineering   78000
7    Robert    Marketing   75000
8    Sophia        Sales   65000
9   William           HR   60000

# Display employee details at position row 5 using iloc.

In [12]:
dataframe.iloc[4]

EmployeeID             205
Name                  Lisa
Department              HR
Salary               58000
Performance Score        4
Years of Service         4
Name: 4, dtype: object

# Display employee details at 208 location using loc.

In [13]:
dataframe.loc[7]

EmployeeID                 208
Name                    Robert
Department           Marketing
Salary                   75000
Performance Score            4
Years of Service             5
Name: 7, dtype: object

# Filter the employees based on the Engineering department.

In [14]:
dataframe[dataframe['Department'] == 'Engineering']

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
0         201  Sarah  Engineering   85000                  4                 5
3         204  David  Engineering   92000                  5                 8
6         207   Emma  Engineering   78000                  3                 2

# Filter the employees based on the salary greater than 70000.

In [15]:
dataframe[dataframe['Salary'] > 70000]

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5

# Filter the employees based on  sales department and performance rating greater than or equal to 4.

In [17]:
dataframe[(dataframe['Department'] == 'Sales') & (dataframe['Performance Score'] >= 4)]

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
5         206   James      Sales   68000                  4                 6
8         209  Sophia      Sales   65000                  5                 4

# Sort employees based on salary in descending order and display top 3 employees.

In [20]:
dataframe.sort_values(['Salary'], ascending=False).head(3)

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
3         204  David  Engineering   92000                  5                 8
0         201  Sarah  Engineering   85000                  4                 5
6         207   Emma  Engineering   78000                  3                 2

# Sort the employees based on Department in ascending order and Salary in descending order.

In [22]:
dataframe.sort_values(['Department', 'Salary'], ascending=[True, False]).reset_index()

,index,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,3,204,David,Engineering,92000,5,8
1,0,201,Sarah,Engineering,85000,4,5
2,6,207,Emma,Engineering,78000,3,2
3,9,210,William,HR,60000,3,3
4,4,205,Lisa,HR,58000,4,4
5,7,208,Robert,Marketing,75000,4,5
6,2,203,Jennifer,Marketing,71000,5,7
7,5,206,James,Sales,68000,4,6
8,8,209,Sophia,Sales,65000,5,4
9,1,202,Michael,Sales,62000,3,3